from typing import List

class SearchResult:
    id: str
    score: float
    index: int

class NanoVectorDB:
    def __init__(self, dims: int) -> None: ...
    def insert(self, id: str, vec: List[float]) -> bool: ...
    def search_graph(self, query_vec: List[float], top_k: int) -> List[SearchResult]: ...
    def search_linear(self, query_vec: List[float], top_k: int) -> List[SearchResult]: ...
    def save_to_file(self, filename: str) -> bool: ...
    def load_from_file(self, filename: str) -> bool: ...
    def size(self) -> int: ...
